### ISSUE TITLE
quote chars in XHP break highlighting

### ISSUE THREAD

**Issue by jra3** [hhvm/hack-mode#12]
Arbitrary text fragments can occur inside of XHP fragments, and if they include a quote char, they are currently treated as the start of a string. This screws up the rest of the buffer.

```
$foo = <nt:text>I don't work</nt:text>;
$now_i_am_string_colored = 42;
```

**Comment by Wilfred** [comment]
Yep, this is going to be tricky to fix. We'll want to do something similar to the JSX modes. rjsx-mode.el has a little XML parser, but that's building on the already complex js2-mode.
