### ISSUE TITLE
Add support for `.hack` files (requires syntax highlighting changes)

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hack-mode#13]
`.hack` files will not require - or allow - leading markup or `<?hh` lines - they're always strict.

See https://github.com/facebook/hhvm/pull/8421 for hack and hackc change, https://github.com/hhvm/vim-hack/pull/46 for a corresponding change to vim

These two files are equivalent:

# foo.php
```hack
<?hh // strict
function foo(): void {
}
```

# foo.hack

```hack
function foo(): void {
}
```

**Comment by Wilfred** [comment]
This already works, but I've updated a comment that claimed that `<?hh` was required in all circumstances.
