### ISSUE TITLE
XHP Highlighting is nonexistent

### ISSUE THREAD

**Issue by sortezia** [hhvm/hack-mode#14]
Hi

I'd like to use hack mode, but currently I don't see have any highlighting on xhp when switching to hack-mode. I'm running emacs version
```
"GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.5.0)
 of 2018-05-28"
```
On a macbook, and I installed hack-mode version `20190214.1612` with commit `c7bf5c750da90d19b6d8011d338dd8617b312e21`. 

Thanks!

**Comment by Wilfred** [comment]
The problem at the moment is that hack-mode isn't aware of XHP, so it treats it as normal Hack code.

What highlighting are you missing? I know we highlight too much in some cases (see #12). Could you give an example?

**Comment by sortezia** [comment]
Hi, thanks for the response!

I've copied the basic snippet from the xhp docs (https://docs.hhvm.com/hack/XHP/basic-usage).

emacs (hack-mode)
<img width="468" alt="screen shot 2019-02-18 at 7 53 06 pm" src="https://user-images.githubusercontent.com/4776597/52989206-37389e80-33b7-11e9-9518-f79524983d18.png">
visual-studio code (https://marketplace.visualstudio.com/items?itemName=pranayagarwal.vscode-hack)
<img width="540" alt="screen shot 2019-02-18 at 7 54 35 pm" src="https://user-images.githubusercontent.com/4776597/52989240-5e8f6b80-33b7-11e9-8976-b5d03c0798ce.png">

There is some *deeply* nested xhp in our repository, and the highlighting on the `<divs>` and assorted html elements (in the vs Code extension) is indispensable. I would much rather use emacs (and am happy to help out here). I want to first confirm that I'm not doing something silly, and that hack-mode doesn't natively support this highlighting out of the box.

**Comment by Wilfred** [comment]
Thanks, that's really helpful.

There's no XHP support in hack-mode yet.

Chatting to Fred, I understand that the vim mode switches to HTML syntax mode on `<abc`, then switches back to Hack mode on `</abc`. I think that would work the majority of the time, although it might be confused by nested tags with the same name: `<span><span></span>foo bar</span>`. It would still be an improvement on today's nonexistent support.

The other option would be to look at what the JSX major modes do.  For example, `rjsx-mode` (based on `js2-mode` which has a full JS parser so it's not very easy to imitate) has `rjsx-parse-xml` which seems to do the tag parsing.

The trick is ensuring that `$foo = <p>hello<p>;` is not confused with `$foo < $bar` or `classname<T>`. I think a dumb analysis would be fine (space, then `<`, then char) but we could look at `next_xhp_element_token` in `full_fidelity_lexer.ml` to see what the actual Hack lexer does.

In addition to highlighting, there's also XHP indentation, which is almost certainly wrong. We don't need to be perfect (that's what `hackfmt` is for) but basic newlines inside XHP fragments we should do the right thing.

**Comment by Wilfred** [comment]
I'm very happy to review patches if this is something you want to work on, and we already have a test suite for highlighting :)

I do plan to fix this at some stage, FWIW. We have Hacklang users using lots of different modes (`hack-mode`, `php-mode`, old forks of `hack-mode`, handrolled modes, HTML modes), and I'd like `hack-mode` to be so good that all our Emacs users prefer it.

**Comment by sortezia** [comment]
Got it, I'll keep that in mind if I end up hacking up something for my current use cases. Thanks for the update!

**Comment by Wilfred** [comment]
OK, I've made hack-mode do the right thing with XHP blocks. It should highlight tag names, and tag contents should not be highlighted (unless interpolated).

This is a pretty big change, so although I've written a bunch of tests, there will probably be bugs. Please report any you come across :)

If you upgrade a running Emacs instance, I strongly recommend that you kill any hack-mode buffers and re-open them.

**Comment by sortezia** [comment]
Nice work - I'll be taking this for a spin today.
