### ISSUE TITLE
Incorrect indentation after pipe (`|>`)

### ISSUE THREAD

**Issue by kq-li** [hhvm/hack-mode#27]
The pipe operator causes all sorts of wonky indentation, especially with anonymous functions embedded:

Expected:
```
function f(int $x): int {       
  return $x                     
    |> g(                       
         $$                            
       )                               
    |> h($$, function (int $x) {  
         return $x * $x;               
       });
  }
```

Actual:
```
function f(int $x): int {            
  return $x                          
    |> g(                            
  $$                                 
)                                    
  |> h($$, function (int $x) {       
  return $x * $x;                    
});                                  
}                                    
```

The actual indentation within the pipe is pretty opinion-based, but it would be nice if the pipes were aligned at least.

**Comment by Wilfred** [comment]
OK, I've made hack-mode aware of pipes, which has definitely improved matters. It's still not as good as it could be on your example.

If you have some other examples of `|>` itself being badly indented, feel free to reopen :)
