### ISSUE TITLE
When switching to hack-mode some files are incorrectly marked as modified

### ISSUE THREAD

**Issue by aorenste** [hhvm/hack-mode#32]
As of c2c032e8c20e841dddadfd111ca36da5c225239a when switching to hack-mode some files get marked as 'modified' when they actually aren't.  This results in emacs asking if the file should be saved when killing the buffer.

(hphp/runtime/ext/reflection/ext_reflection_hni.php in HHVM is an example of a file that does this for me when loaded)

**Comment by Wilfred** [comment]
I'm unable to reproduce this. Does it still occur from a clean Emacs (e.g. `emacs -Q`)? Do you have anything in `hack-mode-hook`?

**Comment by Wilfred** [comment]
OK, it's not sufficient to open the file. I need to switch to `hack-mode` from e.g. `fundamental-mode` and I can reproduce.
