### ISSUE TITLE
Bad highlighting for comments containing XHP

### ISSUE THREAD

**Issue by Wilfred** [hhvm/hack-mode#33]
```
<?hh // partial

use type Facebook\XHP\HTML\{div, i, strong};

class MyBasicUsageExampleClass {
  public function getInt(): int {
    return 4;
  }
}

function basic_usage_examples_get_string(): string {
  return "Hello";
}

function basic_usage_examples_get_float(): float {
  return 1.2;
}

<<__EntryPoint>>
async function basic_usage_examples_embed_hack(): Awaitable<void> {
  \init_docs_autoloader();
  $xhp_float = <i>{basic_usage_examples_get_float()}</i>;

  $xhp =
    <div>
      {(new MyBasicUsageExampleClass())->getInt()}
      <strong>{basic_usage_examples_get_string()}</strong>
      {$xhp_float /* this embeds the <i /> element as a child of the <div /> */}
    </div>;
  echo await $xhp->toStringAsync();
}
```

`<i />` is incorrectly highlighted.

**Comment by jjergus** [comment]
I don't know anything about Emacs (I heard it's a good operating system :D) but is there any way we could reuse the syntax highlighter (and possibly other parts) from https://github.com/slackhq/vscode-hack?

**Comment by Wilfred** [comment]
They're too different I'm afraid. For example, VSCode uses hierarchical syntax classes like `support.type.php`, whereas Emacs has a generic `font-lock-type-face` (although you can extend the hierarchy if you wish).

**Comment by jjergus** [comment]
There is https://github.com/emacs-lsp/lsp-mode, not sure if it handles syntax highlighting but some of the other LSP features could be useful...

**Comment by Wilfred** [comment]
LSP doesn't support syntax highlighting, although it does have a feature where hovering over one variable will highlight the other instances in the same scope. Hack supports that (I think it's the most common LSP event in fact).

**Comment by Wilfred** [comment]
I can no longer reproduce.
