### ISSUE TITLE
fill-paragraph mangles code when used in docblocks

### ISSUE THREAD

**Issue by jra3** [hhvm/hack-mode#7]
With other modes i've used, fill-paragraph (M-q) has reflowed comment blocks sensibly. When I try this with hack-mode, it now naiively reflows all lines with no breaks between as if it were normal text.

the older c-mode based version worked with /* and // comments, and inserted reasonable leaders on new lines (* in the case of block comments, // in the case of line comments that now span multiple lines)

**Comment by Wilfred** [comment]
Hm, this works for me. Given the code:

```php
<?hh

// foo bar baaaaaaaz foo bar baaaaaaaz foo bar baaaaaaaz foo bar baaaaaaaz foo bar baaaaaaaz foo bar baaaaaaaz foo bar baaaaaaaz foo bar baaaaaaaz 
```

`M-q` on the comment produces:

```
<?hh

// foo bar baaaaaaaz foo bar baaaaaaaz foo bar baaaaaaaz foo bar
// baaaaaaaz foo bar baaaaaaaz foo bar baaaaaaaz foo bar baaaaaaaz foo
// bar baaaaaaaz
```

@jra3 could you give an example where it isn't working?

**Comment by jra3** [comment]
I was referring to docblocks

```
/**
 * Thing Thing Thing Thing Thing Thing Thing Thing Thing Thing Thing Thing
 *
 * This runs very quickly
 */
class FooClass extends IntegrationTest {
  use TFooTrait;
}
```

```
 /** * Thing Thing Thing Thing Thing Thing Thing Thing Thing Thing
 Thing Thing * * This runs very quickly */ class FooClass extends
 IntegrationTest { use TFooTrait; }
```

**Comment by Wilfred** [comment]
@jra3 OK, please give this a try. This is more complex than I expected, so I may have missed some corner cases.

**Comment by jra3** [comment]
Seems to be working pretty well! Thanks

**Comment by Wilfred** [comment]
Thanks, that should be fixed now.
